const mongoose = require('mongoose');
const s = new mongoose.Schema({
  companyId: { type: mongoose.Schema.Types.ObjectId, ref: 'Company', required: true, index: true },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  bankName: { type: String, required: true, trim: true, maxlength: 120 },
  contactPerson: { type: String, trim: true, maxlength: 120 },
  email: { type: String, required: true, lowercase: true, trim: true },
  phone: { type: String, required: true, trim: true },
  address: { type: String, required: true, trim: true, maxlength: 400 },
  city: { type: String, trim: true, maxlength: 80 },
  state: { type: String, trim: true, maxlength: 80 },
  pincode: { type: String, trim: true, maxlength: 10 },
  branchName: { type: String, trim: true, maxlength: 120 },
  employeeId: { type: String, trim: true, maxlength: 40 },
  loanTypes: [{ type: String, trim: true, maxlength: 80 }],
  branches: [{ type: String, trim: true, maxlength: 120 }],
  designations: [{ type: String, trim: true, maxlength: 120 }],
  authorisedEmployees: [{
    _id: false,
    employeeId: { type: mongoose.Schema.Types.ObjectId, ref: 'Employee' },
    name: String,
    staffId: String,
    phone: String,
    altPhone: String,
    email: String,
    personalEmail: String,
    designation: String,
    branch: String,
    department: String,
    dateOfJoining: Date,
    status: String,
    employmentRole: String,
    reportingManager: String,
    loanTypeIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'LoanType' }],
    photoUrl: String,
    companyAssignments: [{
      _id: false,
      companyId: { type: mongoose.Schema.Types.ObjectId, ref: 'Company' },
      branches: [String],
    }],
  }],
  loanPolicies: [{
    _id: false,
    loanType: String,
    minimumAge: Number,
    maximumAge: Number,
    minimumMonthlyIncome: Number,
    minimumCibilScore: Number,
    maximumFoir: Number,
    maximumTenure: Number,
    minimumLoanAmount: Number,
    maximumLoanAmount: Number,
    currentVersion: { type: Number, default: 1 },
    cityStateRestriction: String,
    employmentTypeRestriction: String,
    requiredDocuments: [String],
    manualReview: { type: Boolean, default: false },
    active: { type: Boolean, default: true },
    versionHistory: [{ version: Number, updatedAt: Date, settings: mongoose.Schema.Types.Mixed }],
  }],
  termsAccepted: { type: Boolean, default: false },
  informationAccuracyConfirmed: { type: Boolean, default: false },
  authorisationConfirmed: { type: Boolean, default: false },
  dataProtectionAccepted: { type: Boolean, default: false },
  registrationId: { type: mongoose.Schema.Types.ObjectId, ref: 'BankRegistration', index: true },
  ifscCode: { type: String, trim: true, uppercase: true, maxlength: 11 },
  status: { type: String, enum: ['active', 'pending', 'rejected', 'disabled', 'blocked'], default: 'active', index: true },
  selfRegistered: { type: Boolean, default: false },
  reviewedAt: Date,
  reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  deletedAt: { type: Date, default: null, index: true },
}, { timestamps: true });
module.exports = mongoose.model('Bank', s);
